### ISSUE TITLE
Closing File Chooser quits the analyzer

### ISSUE THREAD

**Issue by KarpovSS** [annikovk/idea_log_analyzer#1]
When I click the Cancel button in a file chooser that was open after clicking either "Select directory" or "Select .zip", the application closes.

I would expect it to remain open.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/26511184/160875246-00e62bfc-043d-455c-91bb-579915f77bfb.png">

**Comment by annikovk** [comment]
fixed in 7f429368a6e87e74ff6a1092c4e7e1ac33fbbc7e
